server:
  port: 56082
  use-forward-headers: true
  tomcat:
    basedir: ${user.home}/tomcat/tmp
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto
  servlet:
    context-path: /farming

spring:
  application:
    name: farming
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  resources:
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: 4MB
      max-file-size: 4MB
  datasource:
    url: jdbc:mysql://ip:port/farmingdb?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123434
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-pool-prepared-statement-per-connection-size: 20
      min-idle: 5
      web-stat-filter:
        session-stat-enable: false
        principal-cookie-name: admin
        url-pattern: /*
        session-stat-max-count: 1000
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        enabled: true
        profile-enable: true
        principal-session-name: admin
      max-active: 20
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      aop-patterns: cn.itcast.farming.*.service.*
      filters: config,stat,wall,log4j2
      max-wait: 60000
      filter:
        stat:
          slow-sql-millis: 1
          log-slow-sql: true
      test-on-borrow: false
      stat-view-servlet:
        allow: 127.0.0.1,192.168.163.1
        deny: 192.168.1.73
        url-pattern: /druid/*
        reset-enable: false
        login-password: admin
        login-username: admin
        enabled: true
      pool-prepared-statements: true
      initial-size: 5
      min-evictable-idle-time-millis: 300000
      test-on-return: false

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: cn.itcast.farming.entity
  mapper-locations: classpath:cn/itcast/farming/mapper/*.xml
  global-config:
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
    id-type: 0

my:
  file:
    qiniu:
      secretKey: key
      accessKey: accessKey
      domainOfBucket: http://ptkz95z4z.bkt.clouddn.com

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml